version: '3.3'
services:
  bigdeal_node:
    build: .
    ports:
      - "3000:3000"
    container_name: bigdeal_node
    volumes:
      - "./:/usr/src/app"
      - "bigdeal_node:/usr/src/app/node_modules"
volumes:
  bigdeal_node: